services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile 
    container_name: casilla_electronica_service_app
    networks:
      - grh_network
    depends_on:
      - casilla_electronica_db
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9005:9000"

  web:
    container_name: casilla_electronica_service_web
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8087:80"
    networks:
      - grh_network
    depends_on:
      - app

  casilla_electronica_db:
    container_name: casilla_electronica_service_db
    image: postgres:17
    environment:
      POSTGRES_DB: casilla_electronica_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - grh_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: casilla_electronica_service_frontend
    ports:
      - "5178:5178"    
    networks:
      - grh_network
    volumes:
      - ./frontend:/src

networks:
  grh_network:
    external: true

volumes:
  pgdata:
    driver: local  # volumen nombrado gestionado por Docker :contentReference[oaicite:4]{index=4}
